package telas;

import daoprojeto.Dao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author igor.osouza5
 */
public class AlterarJogadores extends javax.swing.JFrame {

    /**
     * Creates new form AlterarJogadores
     */
    public AlterarJogadores() {
        initComponents();
    }
    public AlterarJogadores(String n, String p, String t) {
        initComponents();
        txtNome.setText(n);
        txtNome.setEnabled(false);
        cmbPosicao.setSelectedItem(p);
        cmbTime.setSelectedItem(t);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        lblPosicao = new javax.swing.JLabel();
        cmbPosicao = new javax.swing.JComboBox<>();
        cmbTime = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar jogadores");
        getContentPane().setLayout(null);

        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(37, 26, 66, 42);
        getContentPane().add(txtNome);
        txtNome.setBounds(109, 26, 210, 42);

        lblTime.setText("Time");
        getContentPane().add(lblTime);
        lblTime.setBounds(37, 126, 66, 43);

        lblPosicao.setText("Posição");
        getContentPane().add(lblPosicao);
        lblPosicao.setBounds(38, 74, 65, 40);

        cmbPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goleiro", "Defensor / Fixo", "Meio Campo / Ala", "Ataque / Pivô" }));
        cmbPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPosicaoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPosicao);
        cmbPosicao.setBounds(109, 74, 210, 40);

        cmbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time A", "Time B", "Time C", "Time D" }));
        getContentPane().add(cmbTime);
        cmbTime.setBounds(109, 126, 210, 43);

        btnSalvar.setText("Salvar Alterações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(107, 197, 210, 50);

        setSize(new java.awt.Dimension(366, 294));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPosicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPosicaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String n, p, t;
        n = txtNome.getText();
        p = cmbPosicao.getSelectedItem().toString();
        t = cmbTime.getSelectedItem().toString();
        try{
            new Dao().alterarJogadores(n, t, p);
            JOptionPane.showMessageDialog(null, "Jogador alterado com sucesso!");
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro" + ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarJogadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbPosicao;
    private javax.swing.JComboBox<String> cmbTime;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
