package telas;

import daoprojeto.Dao;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author igor.osouza5
 */
public class ListarJogadores extends javax.swing.JFrame {

    /**
     * Creates new form ListarJogadores
     */
    public ListarJogadores() {
        initComponents();
        listar();
    }
    
    public void listar(){
        try{
            ResultSet resultado = new Dao().listarJogadores();
            DefaultTableModel tblModelo = (DefaultTableModel) tabelaListar.getModel();
            tblModelo.setRowCount(0);
            
            
            while (resultado.next()){
                String [] linha = {resultado.getString("nome"),
                resultado.getString("posicao"),
                resultado.getString("time")};
                tblModelo.addRow(linha);
            } 
        }catch(ClassNotFoundException|SQLException ex){
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListar = new javax.swing.JTable();
        cmbPosicao = new javax.swing.JComboBox<>();
        cmbTime = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblPosicao = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Jogadores");
        getContentPane().setLayout(null);

        tabelaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Posição", "Time"
            }
        ));
        jScrollPane1.setViewportView(tabelaListar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(2, 100, 670, 240);

        cmbPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goleiro", "Defensor / Fixo", "Meio Campo / Ala", "Ataque / Pivô" }));
        getContentPane().add(cmbPosicao);
        cmbPosicao.setBounds(450, 12, 131, 40);

        cmbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time A", "Time B", "Time C", "Time D" }));
        getContentPane().add(cmbTime);
        cmbTime.setBounds(260, 12, 72, 40);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(81, 12, 90, 40);

        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 26, 50, 20);

        lblTime.setText("Time");
        getContentPane().add(lblTime);
        lblTime.setBounds(200, 30, 60, 16);

        lblPosicao.setText("Posição");
        getContentPane().add(lblPosicao);
        lblPosicao.setBounds(390, 30, 60, 16);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(600, 20, 70, 30);

        setSize(new java.awt.Dimension(691, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String n, p, t;
        n = txtNome.getText();
        p = cmbPosicao.getSelectedItem().toString();
        t = cmbTime.getSelectedItem().toString();
        
        try{
            ResultSet resultado = new Dao().listarNome(n, t, p);
            DefaultTableModel tblModelo = (DefaultTableModel) tabelaListar.getModel();
            tblModelo.setRowCount(0);
            
            
            while (resultado.next()){
                String [] linha = {resultado.getString("nome"),
                resultado.getString("posicao"),
                resultado.getString("time")};
                tblModelo.addRow(linha);
            } 
        }catch(ClassNotFoundException|SQLException ex){
            JOptionPane.showMessageDialog(null,"Entre em contato com o suporte e informe o erro" + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarJogadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbPosicao;
    private javax.swing.JComboBox<String> cmbTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tabelaListar;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
